export const LOADING = 'LOADING';
export const SEARCH_LOADER = 'SEARCH_LOADER';
export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const USER_DETAIL_VIEW = 'USER_DETAIL_VIEW';
export const SELECTED_DETAIL_USERNAME = 'SELECTED_DETAIL_USERNAME';
export const ON_USER_SEARCH = 'ON_USER_SEARCH';